/**
 * Definicoes fixas das variantes de estrategia.
 * Edite aqui para mudar parametros versionados no Git.
 */
export const STRATEGY_VARIANTS = [
  {
    key: "sniper_45s",
    label: "Sniper 45s (Principal)",
    enabled: false,
    decisionMode: "sniper_v2",
    entryMinutesLeft: 0.75,
    targetEntryPrice: 0.20,
    priceEpsilon: 0.08,
    notionalUsd: 1.0,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    minPayoutMultiple: 2.5,
    maxEntryPrice: 0.30
  },
  {
    key: "safe_90s",
    label: "Safe 90s (Conservadora)",
    enabled: false,
    decisionMode: "sniper_v2",
    entryMinutesLeft: 0.90,
    targetEntryPrice: 0.25,
    priceEpsilon: 0.08,
    notionalUsd: 0.75,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    minPayoutMultiple: 2.0,
    maxEntryPrice: 0.35
  },
  {
    key: "aggr_35s",
    label: "Aggressive 35s (Agressiva)",
    enabled: false,
    decisionMode: "sniper_v2",
    entryMinutesLeft: 0.58,
    targetEntryPrice: 0.18,
    priceEpsilon: 0.06,
    notionalUsd: 1.0,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    minPayoutMultiple: 2.5,
    maxEntryPrice: 0.28,
    takeProfitEnabled: true,
    takeProfitPrice: 0.80
  },
  {
    key: "main_2m",
    label: "Main 2m (Baseline A/B)",
    enabled: false,
    decisionMode: "main_2m_mid",
    entryMinutesLeft: 2.0,
    targetEntryPrice: 0.50,
    priceEpsilon: 0.001,
    notionalUsd: 1.0,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    minPayoutMultiple: 1.0,
    maxEntryPrice: 0.99
  },
  {
    key: "cheap_15m_tp35",
    label: "Cheap Revert 15m (TP 0.55 / sem GP fixo / edge 0.05 + micro)",
    enabled: false,
    decisionMode: "cheap_revert",
    entryMinutesLeft: 13.75,
    entryCloseMinutesLeft: 5.0,
    targetEntryPrice: 0.45,
    minEntryPrice: 0.05,
    priceEpsilon: 0.00,
    notionalUsd: 1.0,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    // (1-p)/p >= 1.5  =>  p <= 0.40. Deixa bot entrar mais, sem liberar preco caro demais.
    minPayoutMultiple: 1.5,
    maxEntryPrice: 0.45,
    takeProfitEnabled: true,
    takeProfitPrice: 0.55,
    grossProfitTargetUsd: 0,
    minEdge: 0.05,
    minModelProb: 0.50,
    minBookImbalance: 0.8,
    maxSpreadToEdgeRatio: 0.5,
    paperFillMode: "pessimistic",
    paperEntrySlippageBps: 25,
    paperExitSlippageBps: 35,
    paperSpreadPenaltyFactor: 0.20,
    maxOracleLagMs: 20000,
    maxBinanceLagMs: 6000,
    maxSnapshotAgeMs: 4000,
    sizingMode: "kelly",
    kellyFraction: 0.35,
    kellyMinNotionalUsd: 0.70,
    kellyMaxNotionalUsd: 1.0,
    maxDailyLossUsd: 2.0,
    riskDayTimezone: "America/Sao_Paulo",
    forceExitMinutesLeft: 2.5,
    liveEntryOrderType: "FAK",
    liveExitOrderType: "FAK",
    marketWindowMinutes: 15,
    marketSlugPrefix: "btc-updown-15m",
    marketSeriesSlug: "btc-up-or-down-15m"
  },
  {
    key: "cheap_1h_tp45",
    label: "Cheap Revert 1h (tiers + regime + lag + TP escalonado)",
    enabled: true,
    decisionMode: "cheap_revert",
    entryMinutesLeft: 57.0,
    entryCloseMinutesLeft: 10.0,
    targetEntryPrice: 0.42,
    minEntryPrice: 0.05,
    priceEpsilon: 0.00,
    notionalUsd: 1.0,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    minPayoutMultiple: 2.0,
    maxEntryPrice: 0.42,
    takeProfitEnabled: true,
    takeProfitPrice: 0.45,
    takeProfitLevels: [
      { price: 0.40, fraction: 0.40 },
      { price: 0.45, fraction: 0.40 },
      { price: 0.50, fraction: 0.20 }
    ],
    trailingStopEnabled: true,
    trailingStopActivationPrice: 0.42,
    trailingStopDropCents: 0.05,
    grossProfitTargetUsd: 0,
    minEdge: 0.05,
    // cheap_revert often picks side < 0.50 implied; gate on edge + basic sanity, not absolute >0.50.
    minModelProb: 0.30,
    minBookImbalance: 0.65,
    maxSpreadToEdgeRatio: 0.5,
    maxSumMids: 1.08,
    minSumMids: 0.85,
    binaryDiscountBonus: 0.5,
    regimeGateEnabled: true,
    regimeTrendEdgeMultiplier: 1.25,
    oracleLagBonusEnabled: true,
    oracleLagBonusMinMs: 5000,
    oracleLagBonusMinDelta: 15,
    oracleLagBonusEdge: 0.05,
    entryPriceTiers: [
      { minutesLeftMin: 40, minutesLeftMax: 57, maxPrice: 0.42, minEdge: 0.11 },
      { minutesLeftMin: 20, minutesLeftMax: 40, maxPrice: 0.42, minEdge: 0.07 },
      { minutesLeftMin: 10, minutesLeftMax: 20, maxPrice: 0.42, minEdge: 0.05, minBookImbalance: 0.65 }
    ],
    paperFillMode: "pessimistic",
    paperEntrySlippageBps: 25,
    paperExitSlippageBps: 35,
    paperSpreadPenaltyFactor: 0.20,
    maxOracleLagMs: 20000,
    maxBinanceLagMs: 6000,
    maxSnapshotAgeMs: 4000,
    sizingMode: "kelly",
    kellyFraction: 0.35,
    kellyMinNotionalUsd: 0.70,
    kellyMaxNotionalUsd: 1.0,
    maxDailyLossUsd: 2.0,
    riskDayTimezone: "America/Sao_Paulo",
    forceExitMinutesLeft: 5.0,
    liveEntryOrderType: "FAK",
    liveExitOrderType: "FAK",
    marketWindowMinutes: 60,
    marketSeriesId: "10114",
    marketSeriesSlug: "btc-up-or-down-hourly",
    crossMarketWindowMinutes: 15,
    crossMarketSlugPrefix: "btc-updown-15m",
    crossMarketSeriesSlug: "btc-up-or-down-15m",
    crossMarketMaxDivergence: 0.15,
    crossMarketEdgeBonus: 0.02,
    crossMarketRequired: false
  }
];
