/**
 * Definicoes fixas das variantes de estrategia.
 * Edite aqui para mudar parametros versionados no Git.
 */
export const STRATEGY_VARIANTS = [
  {
    key: "sniper_45s",
    label: "Sniper 45s (Principal)",
    enabled: false,
    decisionMode: "sniper_v2",
    entryMinutesLeft: 0.75,
    targetEntryPrice: 0.20,
    priceEpsilon: 0.08,
    notionalUsd: 1.0,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    minPayoutMultiple: 2.5,
    maxEntryPrice: 0.30
  },
  {
    key: "safe_90s",
    label: "Safe 90s (Conservadora)",
    enabled: false,
    decisionMode: "sniper_v2",
    entryMinutesLeft: 0.90,
    targetEntryPrice: 0.25,
    priceEpsilon: 0.08,
    notionalUsd: 0.75,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    minPayoutMultiple: 2.0,
    maxEntryPrice: 0.35
  },
  {
    key: "aggr_35s",
    label: "Aggressive 35s (Agressiva)",
    enabled: false,
    decisionMode: "sniper_v2",
    entryMinutesLeft: 0.58,
    targetEntryPrice: 0.18,
    priceEpsilon: 0.06,
    notionalUsd: 1.0,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    minPayoutMultiple: 2.5,
    maxEntryPrice: 0.28,
    takeProfitEnabled: true,
    takeProfitPrice: 0.80
  },
  {
    key: "main_2m",
    label: "Main 2m (Baseline A/B)",
    enabled: false,
    decisionMode: "main_2m_mid",
    entryMinutesLeft: 2.0,
    targetEntryPrice: 0.50,
    priceEpsilon: 0.001,
    notionalUsd: 1.0,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    minPayoutMultiple: 1.0,
    maxEntryPrice: 0.99
  },
  {
    key: "cheap_15m_tp35",
    label: "Cheap Revert 15m (TP 0.25 / GP 0.22)",
    enabled: true,
    decisionMode: "cheap_revert",
    entryMinutesLeft: 13.75,
    entryCloseMinutesLeft: 5.0,
    targetEntryPrice: 0.10,
    minEntryPrice: 0.05,
    priceEpsilon: 0.00,
    notionalUsd: 1.0,
    riskGuardsEnabled: true,
    maxConsecutiveLosses: 999,
    rollingLossHours: 24,
    maxRollingLossUsd: 9999,
    minPayoutMultiple: 2.0,
    maxEntryPrice: 0.10,
    takeProfitEnabled: true,
    takeProfitPrice: 0.25,
    grossProfitTargetUsd: 0.22,
    forceExitMinutesLeft: 2.5,
    liveEntryOrderType: "FAK",
    liveExitOrderType: "FAK",
    marketWindowMinutes: 15,
    marketSlugPrefix: "btc-updown-15m",
    marketSeriesSlug: "btc-up-or-down-15m"
  }
];
